### ISSUE TITLE
 [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated in Node.js 12

### ISSUE THREAD

**Issue by ulrichb** [villadora/express-http-proxy#413]
Causing line: 

https://github.com/villadora/express-http-proxy/blob/5bada09cca1567cbb69a6ec3a637f6457f9e9495/app/steps/decorateUserResHeaders.js#L6

See [Node docs.](https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_headers_outgoingmessage_headernames)

**Comment by ulrichb** [comment]
Can be fixed by switching to [`getHeaders()`](https://nodejs.org/api/http.html#http_response_getheaders). (Available since Node 7.7.0)

**Comment by dman777** [comment]
I am hitting this also

**Comment by ConnorWhite** [comment]
Fixed with https://github.com/villadora/express-http-proxy/pull/420

**Comment by leonheess** [comment]
Why was this closed? Still active..

**Comment by leonheess** [comment]
The issue remains because of https://github.com/villadora/express-http-proxy/blob/2aec18894bfe4d06fc61d959cf718c9e1496226e/app/steps/decorateUserResHeaders.js#L13
